name: Build and Deploy to Development Branch

on:
  push:
    branches:
      - main  # or the branch you want to trigger this action on
  # You can also add a manual trigger using 'workflow_dispatch' if needed
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js (adjust version as needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # specify the version of Node.js you are using

      # Install dependencies and build the project
      - name: Install dependencies
        run: |
          cd web
          npm install

      - name: Build project
        run: |
          cd web
          npm run build

      # Move the build output to the docs folder
      - name: Move build to docs
        run: |
          mkdir docs
          mv web/dist docs/dist
          mv web/index.html docs/index.html
          mv web/favicon.ico docs/favicon.ico
          echo "asccidepths.com" > docs/CNAME

      # Add and commit the changes in the docs folder
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/*
          git commit -m "Deploy updated build to docs"
        continue-on-error: true # Prevents workflow failure if there are no changes to commit

      # Wipe and push to the development branch
      - name: Wipe and push to development branch
        run: |
          git fetch origin

          # Switch to the main branch first
          git checkout main

          # Delete the local development branch if it exists
          git branch -D development || echo "No local development branch to delete"

          # Create a fresh development branch from the current state of main
          git checkout -b development

          # Push the new development branch to the remote, force pushing to overwrite it
          git push --force origin development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto-managed token
